export const coffees = [
  {
    id: 1,
    name: "Expresso Tradicional",
    description: "O tradicional café feito com água quente e grãos moídos",
    price: 9.9,
    tags: ["tradicional"],
    img: "./src/assets/images/coffees/expresso-tradicional.png",
  },
  {
    id: 2,
    name: "Expresso Americano",
    description: "Expresso diluído, menos intenso que o tradicional",
    price: 9.9,
    tags: ["tradicional"],
    img: "./src/assets/images/coffees/expresso-americano.png",
  },
  {
    id: 3,
    name: "Expresso Cremoso",
    description: "Café expresso tradicional com espuma cremosa",
    price: 9.9,
    tags: ["tradicional"],
    img: "./src/assets/images/coffees/expresso-cremoso.png",
  },
  {
    id: 4,
    name: "Expresso Gelado",
    description: "Bebida preparada com café expresso e cubos de gelo",
    price: 9.9,
    tags: ["tradicional", "gelado"],
    img: "./src/assets/images/coffees/expresso-gelado.png",
  },
  {
    id: 5,
    name: "Café com Leite",
    description: "Meio a meio café com leite vaporizado",
    price: 9.9,
    tags: ["tradicional", "com leite"],
    img: "./src/assets/images/coffees/cafe-com-leite.png",
  },
  {
    id: 6,
    name: "Latte",
    description: "Café expresso com o dobro de leite e espuma cremosa",
    price: 9.9,
    tags: ["tradicional", "com leite"],
    img: "./src/assets/images/coffees/latte.png",
  },
  {
    id: 7,
    name: "Capuccino",
    description:
      "Bebida com canela feita de doses iguais de café, leite e espuma",
    price: 9.9,
    tags: ["tradicional", "com leite"],
    img: "./src/assets/images/coffees/capuccino.png",
  },
  {
    id: 8,
    name: "Macchiato",
    description:
      "Café expresso misturado com um pouco de leite quente e espuma",
    price: 9.9,
    tags: ["tradicional", "com leite"],
    img: "./src/assets/images/coffees/macchiato.png",
  },
  {
    id: 9,
    name: "Mocaccino",
    description: "Café expresso com calda de chocolate, pouco leite e espuma",
    price: 9.9,
    tags: ["tradicional", "com leite", "com chocolate"],
    img: "./src/assets/images/coffees/mocaccino.png",
  },
  {
    id: 10,
    name: "Chocolate Quente",
    description: "Bebida feita com chocolate dissolvido no leite quente e café",
    price: 9.9,
    tags: ["especial", "com leite", "com chocolate"],
    img: "./src/assets/images/coffees/chocolate-quente.png",
  },
  {
    id: 11,
    name: "Cubano",
    description:
      "Drink gelado de café expresso com rum, creme de leite e hortelã",
    price: 9.9,
    tags: ["especial", "alcoólico", "gelado"],
    img: "./src/assets/images/coffees/cubano.png",
  },
  {
    id: 12,
    name: "Havaiano",
    description: "Bebida adocicada preparada com café e leite de coco",
    price: 9.9,
    tags: ["especial"],
    img: "./src/assets/images/coffees/havaiano.png",
  },
  {
    id: 13,
    name: "Árabe",
    description: "Bebida preparada com grãos de café árabe e especiarias",
    price: 9.9,
    tags: ["especial"],
    img: "./src/assets/images/coffees/arabe.png",
  },
  {
    id: 14,
    name: "Irlandês",
    description: "Bebida a base de café, uísque irlandês, açúcar e chantilly",
    price: 9.9,
    tags: ["especial", "alcoólico"],
    img: "./src/assets/images/coffees/irlandes.png",
  },
];
